package com.q8intouch.ecovve.network.model

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

@JsonClass(generateAdapter = true)
data class EcovveUserPrevOrders(
    @Json(name = "data")
    var `data`: List<Data>
) {
    @JsonClass(generateAdapter = true)
    data class Data(
        @Json(name = "id")
        var id: Int,
        @Json(name = "number")
        var number: String,
        @Json(name = "status")
        var status: String,
        @Json(name = "delivery")
        var delivery: String,
        @Json(name = "address")
        var address: String,
        @Json(name = "total_qty")
        var totalQty: Int,
        @Json(name = "total_price_before_tax")
        var totalPriceBeforeTax: String,
        @Json(name = "tax_val")
        var taxVal: String,
        @Json(name = "total_price_after_tax")
        var totalPriceAfterTax: String,
        @Json(name = "coupon_code")
        var couponCode: String?,
        @Json(name = "user_free_credit")
        var userFreeCredit: String,
        @Json(name = "gift_card_id")
        var giftCardId: Int?,
        @Json(name = "notes")
        var notes: String,
        @Json(name = "user_id")
        var userId: Int,
        @Json(name = "cart_id")
        var cartId: Int,
        @Json(name = "paid")
        var paid: String,
        @Json(name = "payment_option")
        var paymentOption: String,
        @Json(name = "deliver_time")
        var deliverTime: String?,
        @Json(name = "created_at")
        var createdAt: String,
        @Json(name = "updated_at")
        var updatedAt: String,
        @Json(name = "suborder")
        var suborder: List<Suborder>
    ) {
        @JsonClass(generateAdapter = true)
        data class Suborder(
            @Json(name = "id")
            var id: Int,
            @Json(name = "number")
            var number: String,
            @Json(name = "item")
            var item: List<Item>,
            @Json(name = "status")
            var status: String,
            @Json(name = "delivery")
            var delivery: String,
            @Json(name = "total_qty")
            var totalQty: Int,
            @Json(name = "total_price_before_tax")
            var totalPriceBeforeTax: String,
            @Json(name = "tax_val")
            var taxVal: String,
            @Json(name = "total_price_after_tax")
            var totalPriceAfterTax: Float,
            @Json(name = "order_id")
            var orderId: Int,
            @Json(name = "outlet_id")
            var outletId: Int,
            @Json(name = "cafe_notes")
            var cafeNotes: List<Any>,
            @Json(name = "delivery_man_id")
            var deliveryManId: Int?,
            @Json(name = "created_at")
            var createdAt: String,
            @Json(name = "updated_at")
            var updatedAt: String,
            @Json(name = "outlet")
            var outlet: Outlet
        ) {
            @JsonClass(generateAdapter = true)
            data class Item(
                @Json(name = "id")
                var id: String,
                @Json(name = "qty")
                var qty: String,
                @Json(name = "price_after_promotion")
                var priceAfterPromotion: Float,
                @Json(name = "buy_one_get_one_offer")
                var buyOneGetOneOffer: String,
                @Json(name = "outlet_id")
                var outletId: String
            )

            @JsonClass(generateAdapter = true)
            data class Outlet(
                @Json(name = "id")
                var id: Int,
                @Json(name = "name")
                var name: String,
                @Json(name = "address")
                var address: String,
                @Json(name = "longitude")
                var longitude: Double,
                @Json(name = "latitude")
                var latitude: Double,
                @Json(name = "phone")
                var phone: String,
                @Json(name = "status")
                var status: String,
                @Json(name = "has_delivery")
                var hasDelivery: String,
                @Json(name = "tax")
                var tax: String,
                @Json(name = "capacity")
                var capacity: Int,
                @Json(name = "opening")
                var opening: String,
                @Json(name = "closing")
                var closing: String,
                @Json(name = "location")
                var location: String,
                @Json(name = "city_id")
                var cityId: Int,
                @Json(name = "brand_id")
                var brandId: Int,
                @Json(name = "current_orders_number")
                var currentOrdersNumber: Int,
                @Json(name = "area_id")
                var areaId: Int,
                @Json(name = "created_at")
                var createdAt: String,
                @Json(name = "updated_at")
                var updatedAt: String,
                @Json(name = "brand")
                var brand: Brand
            ) {
                @JsonClass(generateAdapter = true)
                data class Brand(
                    @Json(name = "id")
                    var id: Int,
                    @Json(name = "name")
                    var name: String,
                    @Json(name = "description")
                    var description: String,
                    @Json(name = "business_type")
                    var businessType: String,
                    @Json(name = "commission_annual")
                    var commissionAnnual: String,
                    @Json(name = "commission_order_fixed")
                    var commissionOrderFixed: String,
                    @Json(name = "commission_order_percentage")
                    var commissionOrderPercentage: String,
                    @Json(name = "logo")
                    var logo: String,
                    @Json(name = "phone")
                    var phone: String,
                    @Json(name = "address")
                    var address: String,
                    @Json(name = "has_delivery")
                    var hasDelivery: String,
                    @Json(name = "appears_in_search")
                    var appearsInSearch: String,
                    @Json(name = "minimum_charge")
                    var minimumCharge: String,
                    @Json(name = "website")
                    var website: String,
                    @Json(name = "extra_information")
                    var extraInformation: String,
                    @Json(name = "status")
                    var status: String,
                    @Json(name = "city_id")
                    var cityId: Int,
                    @Json(name = "brand_owner_id")
                    var brandOwnerId: Int,
                    @Json(name = "created_at")
                    var createdAt: String,
                    @Json(name = "updated_at")
                    var updatedAt: String
                )
            }
        }
    }
}