package com.q8intouch.ecovve.network.model

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

@JsonClass(generateAdapter = true)
data class EcovveUserResponse(
    @Json(name = "data")
    var `data`: Data
) {
    @JsonClass(generateAdapter = true)
    data class Data(
        @Json(name = "id")
        var id: Int,
        @Json(name = "name")
        var name: String,
        @Json(name = "email")
        var email: String,
        @Json(name = "phone")
        var phone: String,
        @Json(name = "avatar")
        var avatar: String,
        @Json(name = "area")
        var area: String,
        @Json(name = "gender")
        var gender: String,
        @Json(name = "birthday")
        var birthday: String,
        @Json(name = "points")
        var points: Int,
        @Json(name = "free_credit")
        var freeCredit: String,
        @Json(name = "social_media")
        var socialMedia: List<String>,
        @Json(name = "verification_code")
        var verificationCode: String,
        @Json(name = "active")
        var active: Int,
        @Json(name = "email_verified_at")
        var emailVerifiedAt: Any?,
        @Json(name = "city_id")
        var cityId: Int,
        @Json(name = "all_time_habits")
        var allTimeHabits: List<Int>,
        @Json(name = "used_coupons")
        var usedCoupons: List<Int>,
        @Json(name = "created_at")
        var createdAt: String,
        @Json(name = "updated_at")
        var updatedAt: String,
        @Json(name = "deleted_at")
        var deletedAt: String?,
        @Json(name = "notifications")
        var notifications: Notifications,
        @Json(name = "friends")
        var friends: Friends,
        @Json(name = "reviews")
        var reviews: Reviews,
        @Json(name = "sent_requests")
        var sentRequests: SentRequests,
        @Json(name = "received_requests")
        var receivedRequests: ReceivedRequests,
        @Json(name = "received_gift_cards")
        var receivedGiftCards: ReceivedGiftCards,
        @Json(name = "sent_gift_cards")
        var sentGiftCards: SentGiftCards,
        @Json(name = "orders")
        var orders: Orders,
        @Json(name = "employee")
        var employee: Employee,
        @Json(name = "city")
        var city: City,
        @Json(name = "user_setting")
        var userSetting: UserSetting,
        @Json(name = "addresses")
        var addresses: List<AddAddressResponse.Data>,
        @Json(name = "habits")
        var habits: List<Habit>
    ) {


        @JsonClass(generateAdapter = true)
        data class ReceivedGiftCards(
            @Json(name = "current_page")
            var currentPage: Int,
            @Json(name = "data")
            var data: List<DataG>,
            @Json(name = "first_page_url")
            var firstPageUrl: String,
            @Json(name = "from")
            var from: Int,
            @Json(name = "last_page")
            var lastPage: Int,
            @Json(name = "last_page_url")
            var lastPageUrl: String,
            @Json(name = "next_page_url")
            var nextPageUrl: Any?,
            @Json(name = "path")
            var path: String,
            @Json(name = "per_page")
            var perPage: Int,
            @Json(name = "prev_page_url")
            var prevPageUrl: Any?,
            @Json(name = "to")
            var to: Int,
            @Json(name = "total")
            var total: Int
        ) {
            @JsonClass(generateAdapter = true)
            data class DataG(
                @Json(name = "id")
                var id: Int,
                @Json(name = "name")
                var name: String,
                @Json(name = "description")
                var description: String,
                @Json(name = "amount")
                var amount: String,
                @Json(name = "status")
                var status: String,
                @Json(name = "expire_date")
                var expireDate: String,
                @Json(name = "giver_id")
                var giverId: Int,
                @Json(name = "taker_id")
                var takerId: Int,
                @Json(name = "created_at")
                var createdAt: String,
                @Json(name = "updated_at")
                var updatedAt: String
            )
        }

        @JsonClass(generateAdapter = true)
        data class Habit(
            @Json(name = "id")
            var id: Int,
            @Json(name = "user_id")
            var userId: Int,
            @Json(name = "item_id")
            var itemId: Int,
            @Json(name = "probability")
            var probability: Double,
            @Json(name = "habit_time")
            var habitTime: Int,
            @Json(name = "dayofweek")
            var dayofweek: Int,
            @Json(name = "created_at")
            var createdAt: String,
            @Json(name = "updated_at")
            var updatedAt: String
        )

        @JsonClass(generateAdapter = true)
        data class Notifications(
            @Json(name = "current_page")
            var currentPage: Int,
            @Json(name = "data")
            var data: List<DataN>,
            @Json(name = "first_page_url")
            var firstPageUrl: String,
            @Json(name = "from")
            var from: Int,
            @Json(name = "last_page")
            var lastPage: Int,
            @Json(name = "last_page_url")
            var lastPageUrl: String,
            @Json(name = "next_page_url")
            var nextPageUrl: Any?,
            @Json(name = "path")
            var path: String,
            @Json(name = "per_page")
            var perPage: Int,
            @Json(name = "prev_page_url")
            var prevPageUrl: Any?,
            @Json(name = "to")
            var to: Int,
            @Json(name = "total")
            var total: Int
        ) {
            @JsonClass(generateAdapter = true)
            data class DataN(
                @Json(name = "id")
                var id: Int,
                @Json(name = "name")
                var name: String,
                @Json(name = "type")
                var type: String,
                @Json(name = "content")
                var content: String,
                @Json(name = "seen")
                var seen: String,
                @Json(name = "send_to")
                var sendTo: List<String>,
                @Json(name = "created_at")
                var createdAt: String,
                @Json(name = "updated_at")
                var updatedAt: String
            )
        }

        @JsonClass(generateAdapter = true)
        data class SentRequests(
            @Json(name = "current_page")
            var currentPage: Int,
            @Json(name = "data")
            var data: List<DataS>,
            @Json(name = "first_page_url")
            var firstPageUrl: String,
            @Json(name = "from")
            var from: Int,
            @Json(name = "last_page")
            var lastPage: Int,
            @Json(name = "last_page_url")
            var lastPageUrl: String,
            @Json(name = "next_page_url")
            var nextPageUrl: Any?,
            @Json(name = "path")
            var path: String,
            @Json(name = "per_page")
            var perPage: Int,
            @Json(name = "prev_page_url")
            var prevPageUrl: Any?,
            @Json(name = "to")
            var to: Int,
            @Json(name = "total")
            var total: Int
        ) {
            @JsonClass(generateAdapter = true)
            data class DataS(
                @Json(name = "id")
                var id: Int,
                @Json(name = "status")
                var status: String,
                @Json(name = "sender_id")
                var senderId: Int,
                @Json(name = "receiver_id")
                var receiverId: Int,
                @Json(name = "created_at")
                var createdAt: String,
                @Json(name = "updated_at")
                var updatedAt: String
            )
        }

        @JsonClass(generateAdapter = true)
        data class SentGiftCards(
            @Json(name = "current_page")
            var currentPage: Int,
            @Json(name = "data")
            var data: List<DataSG>,
            @Json(name = "first_page_url")
            var firstPageUrl: String,
            @Json(name = "from")
            var from: Int,
            @Json(name = "last_page")
            var lastPage: Int,
            @Json(name = "last_page_url")
            var lastPageUrl: String,
            @Json(name = "next_page_url")
            var nextPageUrl: Any?,
            @Json(name = "path")
            var path: String,
            @Json(name = "per_page")
            var perPage: Int,
            @Json(name = "prev_page_url")
            var prevPageUrl: Any?,
            @Json(name = "to")
            var to: Int,
            @Json(name = "total")
            var total: Int
        ) {
            @JsonClass(generateAdapter = true)
            data class DataSG(
                @Json(name = "id")
                var id: Int,
                @Json(name = "name")
                var name: String,
                @Json(name = "description")
                var description: String,
                @Json(name = "amount")
                var amount: String,
                @Json(name = "status")
                var status: String,
                @Json(name = "expire_date")
                var expireDate: String,
                @Json(name = "giver_id")
                var giverId: Int,
                @Json(name = "taker_id")
                var takerId: Int,
                @Json(name = "created_at")
                var createdAt: String,
                @Json(name = "updated_at")
                var updatedAt: String
            )
        }

        @JsonClass(generateAdapter = true)
        data class ReceivedRequests(
            @Json(name = "current_page")
            var currentPage: Int,
            @Json(name = "data")
            var data: List<DataR>,
            @Json(name = "first_page_url")
            var firstPageUrl: String,
            @Json(name = "from")
            var from: Int,
            @Json(name = "last_page")
            var lastPage: Int,
            @Json(name = "last_page_url")
            var lastPageUrl: String,
            @Json(name = "next_page_url")
            var nextPageUrl: Any?,
            @Json(name = "path")
            var path: String,
            @Json(name = "per_page")
            var perPage: Int,
            @Json(name = "prev_page_url")
            var prevPageUrl: Any?,
            @Json(name = "to")
            var to: Int,
            @Json(name = "total")
            var total: Int
        ) {
            @JsonClass(generateAdapter = true)
            data class DataR(
                @Json(name = "id")
                var id: Int,
                @Json(name = "status")
                var status: String,
                @Json(name = "sender_id")
                var senderId: Int,
                @Json(name = "receiver_id")
                var receiverId: Int,
                @Json(name = "created_at")
                var createdAt: String,
                @Json(name = "updated_at")
                var updatedAt: String
            )
        }

        @JsonClass(generateAdapter = true)
        data class Orders(
            @Json(name = "current_page")
            var currentPage: Int,
            @Json(name = "data")
            var data: List<DataO>,
            @Json(name = "first_page_url")
            var firstPageUrl: String,
            @Json(name = "from")
            var from: Int,
            @Json(name = "last_page")
            var lastPage: Int,
            @Json(name = "last_page_url")
            var lastPageUrl: String,
            @Json(name = "next_page_url")
            var nextPageUrl: Any?,
            @Json(name = "path")
            var path: String,
            @Json(name = "per_page")
            var perPage: Int,
            @Json(name = "prev_page_url")
            var prevPageUrl: Any?,
            @Json(name = "to")
            var to: Int,
            @Json(name = "total")
            var total: Int
        ) {
            @JsonClass(generateAdapter = true)
            data class DataO(
                @Json(name = "id")
                var id: Int,
                @Json(name = "number")
                var number: String,
                @Json(name = "status")
                var status: String,
                @Json(name = "delivery")
                var delivery: String,
                @Json(name = "address")
                var address: String,
                @Json(name = "total_qty")
                var totalQty: Int,
                @Json(name = "total_price_before_tax")
                var totalPriceBeforeTax: String,
                @Json(name = "tax_val")
                var taxVal: String,
                @Json(name = "total_price_after_tax")
                var totalPriceAfterTax: String,
                @Json(name = "coupon_code")
                var couponCode: String,
                @Json(name = "user_free_credit")
                var userFreeCredit: String,
                @Json(name = "gift_card_id")
                var giftCardId: Int,
                @Json(name = "notes")
                var notes: String,
                @Json(name = "user_id")
                var userId: Int,
                @Json(name = "cart_id")
                var cartId: Int,
                @Json(name = "paid")
                var paid: String,
                @Json(name = "payment_option")
                var paymentOption: String,
                @Json(name = "deliver_time")
                var deliverTime: String,
                @Json(name = "created_at")
                var createdAt: String,
                @Json(name = "updated_at")
                var updatedAt: String
            )
        }

        @JsonClass(generateAdapter = true)
        data class City(
            @Json(name = "id")
            var id: Int,
            @Json(name = "name_ar")
            var nameAr: String,
            @Json(name = "name_en")
            var nameEn: String,
            @Json(name = "name_fr")
            var nameFr: String,
            @Json(name = "country_id")
            var countryId: Int,
            @Json(name = "created_at")
            var createdAt: Any?,
            @Json(name = "updated_at")
            var updatedAt: Any?
        )

        @JsonClass(generateAdapter = true)
        data class Employee(
            @Json(name = "id")
            var id: Int,
            @Json(name = "job")
            var job: String,
            @Json(name = "user_id")
            var userId: Int,
            @Json(name = "outlet_id")
            var outletId: Int,
            @Json(name = "state")
            var state: String,
            @Json(name = "created_at")
            var createdAt: String,
            @Json(name = "updated_at")
            var updatedAt: String
        )

        @JsonClass(generateAdapter = true)
        data class Reviews(
            @Json(name = "current_page")
            var currentPage: Int,
            @Json(name = "data")
            var `data`: List<Any>,
            @Json(name = "first_page_url")
            var firstPageUrl: String,
            @Json(name = "from")
            var from: Any?,
            @Json(name = "last_page")
            var lastPage: Int,
            @Json(name = "last_page_url")
            var lastPageUrl: String,
            @Json(name = "next_page_url")
            var nextPageUrl: Any?,
            @Json(name = "path")
            var path: String,
            @Json(name = "per_page")
            var perPage: Int,
            @Json(name = "prev_page_url")
            var prevPageUrl: Any?,
            @Json(name = "to")
            var to: Any?,
            @Json(name = "total")
            var total: Int
        )

        @JsonClass(generateAdapter = true)
        data class Friends(
            @Json(name = "current_page")
            var currentPage: Int,
            @Json(name = "data")
            var data: List<DataF>,
            @Json(name = "first_page_url")
            var firstPageUrl: String,
            @Json(name = "from")
            var from: Int,
            @Json(name = "last_page")
            var lastPage: Int,
            @Json(name = "last_page_url")
            var lastPageUrl: String,
            @Json(name = "next_page_url")
            var nextPageUrl: Any?,
            @Json(name = "path")
            var path: String,
            @Json(name = "per_page")
            var perPage: Int,
            @Json(name = "prev_page_url")
            var prevPageUrl: Any?,
            @Json(name = "to")
            var to: Int,
            @Json(name = "total")
            var total: Int
        ) {
            @JsonClass(generateAdapter = true)
            data class DataF(
                @Json(name = "id")
                var id: Int,
                @Json(name = "name")
                var name: String,
                @Json(name = "email")
                var email: String,
                @Json(name = "phone")
                var phone: String,
                @Json(name = "avatar")
                var avatar: String,
                @Json(name = "area")
                var area: String,
                @Json(name = "gender")
                var gender: String,
                @Json(name = "birthday")
                var birthday: String,
                @Json(name = "points")
                var points: Int,
                @Json(name = "free_credit")
                var freeCredit: String,
                @Json(name = "social_media")
                var socialMedia: List<String>,
                @Json(name = "verification_code")
                var verificationCode: String,
                @Json(name = "active")
                var active: Int,
                @Json(name = "email_verified_at")
                var emailVerifiedAt: Any?,
                @Json(name = "city_id")
                var cityId: Int,
                @Json(name = "all_time_habits")
                var allTimeHabits: List<Int>,
                @Json(name = "used_coupons")
                var usedCoupons: List<Int>,
                @Json(name = "created_at")
                var createdAt: String,
                @Json(name = "updated_at")
                var updatedAt: String,
                @Json(name = "deleted_at")
                var deletedAt: Any?
            )
        }

        @JsonClass(generateAdapter = true)
        data class UserSetting(
            @Json(name = "id")
            var id: Int,
            @Json(name = "notification")
            var notification: String,
            @Json(name = "report_type")
            var reportType: String,
            @Json(name = "language")
            var language: String,
            @Json(name = "user_id")
            var userId: Int,
            @Json(name = "created_at")
            var createdAt: String,
            @Json(name = "updated_at")
            var updatedAt: String
        )
    }
}